### ISSUE TITLE
File sharing not found

### ISSUE THREAD

**Issue by ronygolderku** [wekeo/ai4EM_MOOC#1]
Hello,
The readme files shows
_It is important to know that the following GitHub repository ONLY contains the Jupyter notebooks WITHOUT the data utilized for the notebooks. The data that is needed for each week can be found below:_
_Week 1
Week 2
Week 3
Week 4
Week 5
Week 6_

But, the links attached to week1 show files and other the the links for week2 to week6 is not working.

Could you please fix the issue?

Thanks in advance.

**Comment by cfortunylombra** [comment]
Hi, 

I am very sorry for the late reply. 
 
The shared files have been updated, and the expiration date has been removed. Hence, the issue has been fixed.

Thank you for pointing this out.

Kind regards,
Carlos
